ModelEngine-Group/fit-framework

- framework/elsa/fit-elsa-react/.gitignore
- framework/elsa/fit-elsa-react/index.html
[elsa] 修改.gitignore中文件范围，提交index.html文件。修复elsa-react在运行npm run dev命令后无法启动的问题
> [elsa] 修复elsa-react在运行npm run dev命令后无法启动的问题

- .github/workflows/elsa-compile.yml
[elsa] 添加elsa目录会触发的github actions配置 ，支持main分支和x.x.x分支的PR和Push触发
> [elsa] 添加elsa相关的github actions配置 

- framework/elsa/fit-elsa-react/src/flow/jadeFlowPage.js
[elsa] testRun逻辑修改，对返回的nodes排序，令后续状态刷新时按顺序进行
> [elsa] 优化testRun逻辑，避免返回的nodes顺序与流的顺序不一致，发生刷新状态错序的问题

- framework/elsa/fit-elsa-react/src/components/flowRunComponent/SectionFactory.jsx
> [elsa] 修复条件节点运行结果空指针问题

- framework/elsa/fit-elsa-react/src/components/llm/LlmFormWrapper.jsx
[elsa] 修复大模型节点工具对应插件/工作流被卸载/删除后，在编排页面中对应插件/工作流的选项不会被展示的问题
> [elsa] 修复大模型节点工具对应插件/工作流被卸载/删除后，编排页面未进行展示的问题

- framework/elsa/fit-elsa-react/src/components/start/AppConfiguration.jsx
- framework/elsa/fit-elsa-react/src/components/start/StartFormWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/start/startComponent.jsx
- framework/elsa/fit-elsa-react/src/data/GraphOperator.js
- framework/elsa/fit-elsa-react/src/en_US.json
- framework/elsa/fit-elsa-react/src/testFlowData.js
- framework/elsa/fit-elsa-react/src/zh_CN.json
> [elsa] 开始节点添加应用配置

- .github/workflows/framework-java-compile.yml
[framework] 添加 java 框架的 github action文件，包括examples和framework下的除了python和elsa目录
> [framework] 添加 java 框架的 github action 文件

- framework/elsa/fit-elsa-react/src/flow/jadeFlowPage.js
[elsa] 修改elsa-react中对core的引用路径统一至@fit-elsa/elsa-core
> [elsa] 修改elsa-react中对core的引用路径

- framework/elsa/fit-elsa-react/src/components/base/jadeNode.jsx
[elsa] 修复大模型节点前有环路的情况下无法流式输出的问题，具体情况是环路中有人工节点时，递归逻辑有误
> [elsa] 修复大模型节点前有环路的情况下无法流式输出的问题

- framework/elsa/fit-elsa-react/src/components/DefaultRoot.jsx
- framework/elsa/fit-elsa-react/src/components/base/jadeNode.jsx
- framework/elsa/fit-elsa-react/src/components/common/style.css
- framework/elsa/fit-elsa-react/src/components/condition/ConditionFormWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/condition/conditionComponent.jsx
- framework/elsa/fit-elsa-react/src/components/defaultComponent.js
- framework/elsa/fit-elsa-react/src/components/headerStyle.css
- framework/elsa/fit-elsa-react/src/components/note/noteNode.jsx
- framework/elsa/fit-elsa-react/src/components/questionClassification/QuestionClassificationPanel.jsx
- framework/elsa/fit-elsa-react/src/components/questionClassification/QuestionClassificationWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/questionClassification/questionClassificationComponent.jsx
- framework/elsa/fit-elsa-react/src/flow/jadeFlowEntry.jsx
- framework/elsa/fit-elsa-react/src/testFlowData.js
- framework/elsa/fit-elsa/core/shape.js
> [elsa] 增加图形点击后弹出抽屉进行配置的代码

- framework/fit/java/fit-builtin/services/fit-http-classic/definition/src/main/java/modelengine/fit/http/client/support/TextStreamChoir.java
> [fit] 捕获流式调用报错信息

- framework/elsa/fit-elsa-react/src/components/code/CodePanel.jsx
[elsa] 修复代码节点精简模式报错的问题，避免代码节点折叠
> [elsa] 修复代码节点精简模式报错的问题

- framework/elsa/fit-elsa-react/src/common/Consts.js
[elsa] 修复循环节点新增字段数据格式问题，修复循环节点无法保存的错误
> [elsa] 修复循环节点新增字段数据格式问题

- framework/elsa/fit-elsa-react/src/components/intelligentForm/FormItemSelectValue.jsx
[elsa] 修复智能编排表单节点在表单选项输入值时，可能出现的数据格式不正确问题
对应issue：https://github.com/ModelEngine-Group/fit-framework/issues/40
> [elsa] 修复智能编排表单节点在表单选项输入值时，可能出现的数据格式不正确问题

- framework/elsa/fit-elsa-react/src/components/DefaultRoot.jsx
> [elsa] 修复注释节点无法编辑的问题

- framework/elsa/fit-elsa-react/src/flow/jadeFlowPage.js
- framework/elsa/fit-elsa-react/src/testFlowData.js
[elsa] 优化节点排序逻辑，让同节点多连线按连接点顺序排列
> [elsa] 优化节点排序逻辑

- framework/elsa/fit-elsa-react/src/components/base/baseToolNode.jsx
- framework/elsa/fit-elsa-react/src/components/fitInvokeNode/fitInvokeComponent.jsx
- framework/elsa/fit-elsa-react/src/components/loopNode/SkillForm.jsx
- framework/elsa/fit-elsa-react/src/components/manualCheck/ManualCheckForm.jsx
- framework/elsa/fit-elsa-react/src/components/textExtraction/reducers.js
- framework/elsa/fit-elsa-react/src/components/util/MethodMetaDataParser.js
[elsa] 增强对元数据schema的判断，只有required为列表时才处理，其余都默认为false
> [elsa] 增强对元数据schema的判断，避免错误schema影响处理逻辑

- framework/elsa/fit-elsa-react/src/components/base/jadeNode.jsx
[elsa] 1.修复获取测试报告时因为后端数据修改导致的空指针问题 2.避免非法json导致的报错
> [elsa] 获取测试报告的代码鲁棒性增强

- framework/elsa/fit-elsa-react/src/components/retrieval/KnowledgeForm.jsx
SELECT_KNOWLEDGE_BASE_GROUP事件增加selectedGroupId的传参，方便前端渲染已选的值
> [elsa] SELECT_KNOWLEDGE_BASE_GROUP事件增加selectedGroupId的传参

- framework/elsa/fit-elsa-react/src/common/Consts.js
- framework/elsa/fit-elsa-react/src/components/intelligentForm/Consts.js
- framework/elsa/fit-elsa-react/src/components/intelligentForm/FormItemFieldType.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/FormItemRenderType.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/FormItemSelectValue.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/IntelligentInputFormItem.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/reducers.js
- framework/elsa/fit-elsa-react/src/en_US.json
- framework/elsa/fit-elsa-react/src/zh_CN.json
智能编排表单节点增强，支持图片显示，支持Select，CheckBox，Label展示形式
> [elsa] 智能编排表单节点增强

- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/SearchForm.jsx
> [elsa] 隐藏知识检索的重排选项

- framework/fel/java/maven-plugins/tool-maven-plugin/src/main/java/modelengine/fel/maven/complie/plugin/UrlClassLoaderInitializer.java
- framework/fit/java/fit-builtin/plugins/fit-message-serializer-json-jackson/src/main/java/modelengine/fit/serialization/json/jackson/JacksonObjectSerializer.java
- framework/fit/java/fit-builtin/plugins/fit-message-serializer-json-jackson/src/test/java/modelengine/fit/serialization/json/jackson/JacksonObjectSerializerTest.java
优化代码节点中，由于入参为null，导致序列化将对应的key值删除的问题
> [fit] 优化序列化器逻辑

- framework/elsa/fit-elsa-react/src/components/intelligentForm/FormItemSelectValue.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/IntelligentFormWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/IntelligentInputFormItem.jsx
- framework/elsa/fit-elsa-react/src/components/start/StartFormWrapper.jsx
1.智能表单更换字段类型时，清空默认值
2.智能表单和开始节点强制渲染Panel内元素
> [elsa] 修复智能表单问题

- framework/elsa/fit-elsa-react/src/components/llm/Model.jsx
[elsa] 大模型节点模型下拉框宽度根据下拉选项内容长度自适应
> [elsa] 大模型节点模型下拉框宽度自适应

- framework/elsa/fit-elsa-react/src/common/Consts.js
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/KnowledgeRetrievalWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalComponent.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalNodeState.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/reducers.js
- framework/elsa/fit-elsa-react/src/components/retrieval/KnowledgeForm.jsx
- framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js
[elsa] 知识检索节点去除userId入参，在option中增加knowledgeConfigId参数
> [elsa] 知识检索节点参数修改

- framework/elsa/fit-elsa-react/src/common/Consts.js
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/KnowledgeRetrievalWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalComponent.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalNodeState.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/reducers.js
- framework/elsa/fit-elsa-react/src/components/llm/Model.jsx
- framework/elsa/fit-elsa-react/src/components/retrieval/KnowledgeForm.jsx
- framework/elsa/fit-elsa-react/src/data/GraphOperator.js
- framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js
1.Auto-resize the large model node dropdown width to fit its content.
2.Modify knowledge retrieval node data struct.
3.Modify the update method in GraphOperator.js to automatically add a value if it does not exist during an update operation.
> [elsa] Fix bugs of 0.1.x.

- framework/elsa/fit-elsa-react/src/data/GraphOperator.js
- Move reference-type check before object-type handling
- Strengthen type comparison with case-insensitive check
- Add null-safe conversion using String() and nullish coalescing
- Maintain same protection logic but with more robust implementation
> [elsa] enhance reference-type config protection

- framework/fel/java/services/tool-info/pom.xml
update too-info parent to fix action fail
> [fel] update tool-info parent

- framework/fel/python/requirements.txt
**Issue 链接 / Issue Link:** #
添加 code 节点中新引入的三方包的版本号
Add version numbers for newly introduced third-party packages in the code node
- 添加版本号：httpx==0.28.1 pandas==2.1.3
- Add version numbers: httpx==0.28.1, pandas==2.1.3
1. 流水线编译正常，可以正常出包 / Pipeline builds successfully and packages are generated as expected.
2. 部署环境中执行import命令可以正确执行 / The import statement works properly in the deployment environment.
1. 流水线出包，可以正确安装对应版本的包 / The pipeline successfully builds the package and can correctly install the specified version of the dependencies.
2. 安装部署后，进入python容器后，执行 pip list 可以看到正确的版本号 / After installation and deployment, running pip list inside the Python container shows the correct version numbers.
3. 部署环境在 code 节点中 import 对应的三方包正确执行 / In the deployment environment, importing the third-party …
> [python] update code node whitelist version

- framework/elsa/fit-elsa-react/src/components/intelligentForm/Consts.js
- framework/elsa/fit-elsa-react/src/components/intelligentForm/IntelligentFormWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/SimpleFormWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/intelligentFormComponent.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/intelligentFormNodeState.jsx
- framework/elsa/fit-elsa-react/src/components/intelligentForm/reducers.js
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalComponent.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/reducers.js
- framework/elsa/fit-elsa-react/src/components/llm/llmComponent.jsx
- framework/elsa/fit-elsa-react/src/components/loopNode/LoopConsts.js
- framework/elsa/fit-elsa-react/src/components/loopNode/loopComponent.jsx
- framework/elsa/fit-elsa-react/src/components/parallelNode/parallelComponent.jsx
- framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js
- framework/elsa/fit-elsa-react/src/i18n/en_US.json
- framework/elsa/fit-elsa-react/src/i18n/zh_CN.json
**Issue 链接 / Issue Link:** #50 
归一智能编排表单和人工表单
- 表单归一
- 老数据兼容适配
1. 创建新表单正常
2. 老表单自动兼容
---
> [elsa] refactor(NodeState): unify intelligentForm and manualCheck node states

- framework/elsa/fit-elsa-react/package.json
**Issue 链接 / Issue Link:** #202 
令elsa可以正常编译
- 修改package.json中 重写rollup的版本 写死为 4.39.0
1. 重写后编译出包正常
> [elsa] Force lock the Rollup version to 4.39.0.

- framework/elsa/fit-elsa-react/src/common/Consts.js
- framework/elsa/fit-elsa-react/src/components/common/prompt/Prompt.jsx
- framework/elsa/fit-elsa-react/src/components/llm/LlmFormWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/llm/McpConfigForm.jsx
- framework/elsa/fit-elsa-react/src/components/llm/ModelForm.jsx
- framework/elsa/fit-elsa-react/src/components/llm/llmComponent.jsx
- framework/elsa/fit-elsa-react/src/components/llm/reducers/reducers.js
- framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js
- framework/elsa/fit-elsa-react/src/i18n/en_US.json
- framework/elsa/fit-elsa-react/src/i18n/zh_CN.json
**Issue 链接 / Issue Link:** [#318](https://github.com/ModelEngine-Group/app-platform/issues/318)
令大模型节点可以配置MCPServer相关值
- 大模型节点增加MCPServer配置
1. 对配置项进行输入，输入正确的json后，成功保存
2. 对配置项进行输入，输入错误的json后，保存的仍是此前最后一次的正确json
---
> [elsa] Add MCPServerConfig configuration to the large model node.

- framework/fit/python/fitframework/__init__.py
**Issue 链接 / Issue Link:** #94 
Starting with Python 3.8, macOS uses the spawn method by default, identical to Windows.
The previous while True + Process respawn loop is therefore unnecessary on macOS.
This change unifies the startup behavior between Windows and macOS, keeping the auto-restart guard only on Linux, and eliminates redundant processes and log noise for macOS users.
- Extended platform check from platform.system() == 'Windows' to platform.system() in ('Windows', 'Darwin').
- macOS now calls main() once and exits, matching Windows behavior.
- Linux retains the existing while True + Process respawn logic.
1. Run the entry script on Windows → observe one main() invocation, then exit.
2. Run the entry script on macOS → same single invocation, no respawn loop.
3. Run the entry …
> fix: stop respawning on macOS, align with Windows behavior

- framework/elsa/fit-elsa-react/src/common/Consts.js
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/KnowledgeRetrievalWrapper.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/OutsideRerankForm.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/SearchForm.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalComponent.jsx
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/reducers.js
- framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js
- framework/elsa/fit-elsa-react/src/i18n/en_US.json
- framework/elsa/fit-elsa-react/src/i18n/zh_CN.json
**Issue 链接 / Issue Link:** #230 
Elsa在知识检索节点中增加重排相关UI
- 增加重排相关UI以及对应的数据结构
1. 打开重排相关UI，操作是否选择重排，效果符合预期
2. 选择重排相关模型，效果符合预期
3. 修改重排的TopN，效果符合预期
4. 修改知识检索的TopK，重排TopN会联动
5. 以上每个修改依次触发聊天，知识检索节点调用返回结果符合预期
- [] 我已经编写了必要的单元测试来验证逻辑正确性 / I have written necessary unit-tests to verify the logic correction
---
> [elsa] knowledge node add rerank UI

- README.md
**Issue 链接 / Issue Link:** fix #232 
- 优化启动命令所在的目录，确保执行成功
- 优化解释说明，明确告知无法启动的目录情况
1. 按照文档，进行启动，可以启动成功
---
> Documentation: optimize FIT readme

- framework/fel/python/plugins/builtins/fit_py_code_node_tools/conf/application.yml
- framework/fel/python/plugins/builtins/fit_py_code_node_tools/python_repl_impl.py
**Issue 链接 / Issue Link:** #
code 节点白名单 asyncio 涉及安全问题，需要在白名单中去除 / The code node whitelist contains issues related to security in asyncio, which needs to be removed from the whitelist
-  删除白名单中的 asyncio 包 / Remove the asyncio package from the whitelist
1.  code 节点中使用 asyncio 执行失败 /  Failed to execute using asyncio in the code node 
---
> [fel] Remove asyncio from the whitelist

- framework/elsa/fit-elsa-react/src/i18n/en_US.json
- framework/elsa/fit-elsa-react/src/i18n/zh_CN.json
**Issue 链接 / Issue Link:** #177 
修复code节点说明错误问题
- 修改code节点国际化素材
1. 启动modelengine
2. 查看code节点说明
3. 说明正常
---
> 修复code节点说明错误问题

- framework/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/OpenAiModel.java
- framework/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/config/OpenAiConfig.java
**Issue 链接 / Issue Link:** #255
解决大模型对话接口，apikey 校验报错的问题。
- 当传入的 apikey 为 null 或空时，调用服务接入大模型对话接口时，header 里不传入 authorization 字段
- 当传入的 apikey 非空时，调用服务接入大模型对话接口时，header 里加上 authorization 字段
1. 在模型工程部署自定义模型。
2. 在服务接入自定义模型。
3. 在应用开发调试页面，大模型节点选中服务接入的模型。
4. 点击调试。
---
> [FEL] remove apikey header while input apikey is null

- framework/fit/java/fit-builtin/plugins/fit-http-server-netty/src/main/java/modelengine/fit/http/server/netty/HttpClassicRequestAssembler.java
**Issue 链接 / Issue Link:** #265
1. 使 NettyHttpServerResponse 不要提前关闭 / Make NettyHttpServerResponse not close prematurely
1. 进行调试对话，前端能正常显示所有回答 / Conduct debugging dialogue, and the front end can display all answers normally.
---
> [fit] keep NettyResponse from closing prematurely

- framework/elsa/fit-elsa-react/src/common/Consts.js
- framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalComponent.jsx
- framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js
**Issue 链接 / Issue Link:** #269
增加Elsa知识库参数的扩展字段 / Add elsa extended fields for knowledge parameters.
1. 上层进行知识库调用时，增加扩展字段的值 / When the upper layer calls the knowledge, the value of the extension field is increased.
2. 调用时候看看该值有没有存在 / Check if the value exists when calling
---
> [elsa] add knowledgeExtensions params of knowledgeRetrievalNode option struct.

- framework/fit/java/fit-builtin/services/fit-http-classic/definition/src/main/java/modelengine/fit/http/support/DefaultSerializers.java
**Issue 链接 / Issue Link:** #292 
为 text/html 和 text/css 增加序列化器支持
- 在默认序列化器选择的时候，为 text/css 和 text/html 增加文本序列化器的映射
1. 全量编译，测试通过
2. 待获取用户场景，再进行测试
---
> [fit] add text/* mimetype for text serializer

- framework/elsa/fit-elsa-react/src/components/variableUpdate/VariableUpdateInputForm.jsx
- framework/elsa/fit-elsa-react/src/components/variableUpdate/variableUpdateComponent.jsx
- framework/elsa/fit-elsa-react/src/components/variableUpdate/variableUpdateNodeState.jsx
**Issue 链接 / Issue Link:** <mark>#317</mark> 👈👈
修复变量更新节点，小框输入和大框输入不同步的问题。
- 修改变量更新节点相关代码
1. 正常部署服务
---
> [Elsa] bugfix: fix variable update node bugs

- framework/fit/java/fit-runtime/src/main/resources/fitframework.yml
**Issue 链接 / Issue Link:** <mark> #306  </mark> 👈👈
-  增加了注册中心相关的默认配置
- 
- 
1. 
2. 
3. 
---
> [fit] 增加 fit 注册中心默认配置
