docs/framework/fit/java/user-guide-book/07. 数据访问.md, framework/fit/java/integration/fit-mybatis/pom.xml, framework/fit/java/integration/fit-mybatis/src/main/java/modelengine/fit/integration/mybatis/MybatisBeanContainerInitializedObserver.java, framework/fit/java/integration/fit-mybatis/src/test/java/modelengine/fit/integration/mybatis/WordMapperTest.java, framework/fit/java/integration/fit-mybatis/src/test/java/modelengine/fit/integration/mybatis/mapper/WordMapper.java, framework/fit/java/integration/fit-mybatis/src/test/java/modelengine/fit/integration/mybatis/model/WordDo.java, framework/fit/java/integration/fit-mybatis/src/test/resources/application.yml, framework/fit/java/integration/fit-mybatis/src/test/resources/mapper/WordMapper.xml, framework/fit/java/integration/fit-mybatis/src/test/resources/sql/create/word.sql
提供配置项 map-underscore-to-camelcase，默认为 false
``` yaml
mybatis:
mapper-locations: 'mapper/*.xml'
map-underscore-to-camelcase: true
```
note: 查阅资料发现 mybatis 暂时只提供该配置，蛇形转化等配置未提供 
#1
=> 支持 mybatis 配置自动下划线转驼峰：mybatis.map-underscore-to-camelcase

framework/elsa/fit-elsa-react/package.json, framework/elsa/fit-elsa/package.json
[elsa] 升级axios从1.7.4至1.8.2，webpack从5.89.0至5.94.0，解决原有版本的漏洞问题
=> [elsa] 升级依赖axios和webpack至无漏洞的版本

framework/elsa/fit-elsa-react/src/flow/jadeFlowPage.js, framework/elsa/fit-elsa/core/page.js
[elsa] elsa-react默认操作由指针选中改为手型拖拽，优化用户体验
=> [elsa] elsa-react默认操作由选中改为拖拽画布

framework/ohscript/src/main/java/modelengine/fit/ohscript/util/Tool.java
[ohscript] 修改ohscript生成随机uuid方式，提升性能
=> [ohscript] 修改ohscript生成随机uuid方式提升性能

framework/fit/java/fit-builtin/plugins/fit-security-simple/pom.xml, framework/fit/java/fit-builtin/plugins/fit-security-simple/src/main/java/modelengine/fit/security/simple/SimpleCipher.java, framework/fit/java/fit-builtin/plugins/fit-security-simple/src/main/resources/application.yml, framework/fit/java/fit-builtin/plugins/pom.xml
[fit] 添加fit-security-simple插件，用于提供加解密的空实现
=> [fit] 添加fit-security-simple插件

framework/fit/java/fit-broker/src/main/java/modelengine/fitframework/broker/support/MulticastFitableExecutor.java, framework/fit/java/fit-broker/src/main/java/modelengine/fitframework/broker/support/MulticastGenericableExecutor.java
[fit] 修复广播模式下如果genericable无返回值时的报错问题
=> [fit] 修复广播模式下如果genericable无返回值时的报错问题

framework/elsa/fit-elsa-react/src/components/common/JadePanelHeader.jsx, framework/elsa/fit-elsa-react/src/components/end/EndInputForm.jsx, framework/elsa/fit-elsa-react/src/components/end/OutputVariable.jsx, framework/elsa/fit-elsa-react/src/en_US.json, framework/elsa/fit-elsa-react/src/zh_CN.json
[elsa] 由于原提示有误，讨论后决定去除结束节点直接输出结果中的提示
=> [elsa] 去除结束节点直接输出结果中输出的popover

framework/elsa/fit-elsa-react/src/common/Consts.js, framework/elsa/fit-elsa-react/src/components/loopNode/loopComponent.jsx, framework/elsa/fit-elsa-react/src/components/loopNode/loopNodeState.jsx, framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js, framework/elsa/fit-elsa-react/src/shapes/systemEnv.jsx
[elsa] 循环节点增加默认的context入参，用于循环节点中止
=> [elsa] 循环节点增加默认的context入参

framework/elsa/fit-elsa-react/src/components/note/editor.css
[elsa] 注释节点强制列表样式，解决部署大包时样式被覆盖导致无法显示列表样式的问题
=> [elsa] 注释节点强制列表样式

framework/elsa/fit-elsa-react/src/components/base/jadeNodeDrawer.jsx
[elsa] 修复保存运行中节点的脏数据后，重新打开应用时，节点尚未渲染时，drawAnimation调用导致的空指针问题
=> [elsa] 修复页面打开应用时持续转圈无法操作的问题

framework/elsa/fit-elsa-react/src/common/Consts.js, framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalComponent.jsx, framework/elsa/fit-elsa-react/src/components/knowledgeRetrieval/knowledgeRetrievalNodeState.jsx, framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js
=> [elsa] 知识检索节点添加userId入参

framework/fit/python/requirements.txt
python 当前依赖的三方包存在安全问题，需要升级 requests 与 tornado 这两个三方包的版本解决安全问题
=> [python] 升级 python 依赖三方包的版本

framework/elsa/fit-elsa-react/src/components/DefaultRoot.jsx, framework/elsa/fit-elsa-react/src/components/base/jadeNode.jsx
[elsa] 交互逻辑修改
1. 编排时单击空白处自动关闭详情窗口
2. 点击关闭详情窗口时，对应shape去除选中状态
=> [elsa] 交互逻辑修改

framework/elsa/fit-elsa-react/src/components/variableAggregation/VariableAggregationInputForm.jsx
[elsa] typeFilter对入参o的属性增加空指针校验
=> [elsa] typeFilter对入参o的属性增加空指针校验

framework/elsa/fit-elsa-react/src/components/note/TextEditor.jsx, framework/elsa/fit-elsa-react/src/components/note/editor.css
[elsa] 指定ol和ul对应样式的适配范围，限定用于mce-content-body这个className下
=> [elsa] 指定ol和ul对应样式的适配范围

framework/elsa/fit-elsa-react/src/components/note/editor.css
[elsa] 注释节点对于有序列表和无序列表中的li标签也要强制指定list-style-type的css，避免三合一部署时被其他样式覆盖
=> [elsa] 修改注释节点列表中li标签的样式

framework/elsa/fit-elsa/core/atom.js
序列化保存时改为同步调用，避免异步调用导致可能的错误的状态保存
=> [elsa] 序列化保存改同步

framework/elsa/README.md
=> [elsa] 添加README

framework/elsa/fit-elsa-react/src/common/Consts.js, framework/elsa/fit-elsa-react/src/components/asserts/icon-parallel.svg, framework/elsa/fit-elsa-react/src/components/common/InvokeInput.jsx, framework/elsa/fit-elsa-react/src/components/common/JadeInputTreeCollapse.jsx, framework/elsa/fit-elsa-react/src/components/loopNode/LoopConsts.js, framework/elsa/fit-elsa-react/src/components/loopNode/LoopWrapper.jsx, framework/elsa/fit-elsa-react/src/components/loopNode/SkillForm.jsx, framework/elsa/fit-elsa-react/src/components/loopNode/loopComponent.jsx, framework/elsa/fit-elsa-react/src/components/loopNode/reducers/reducers.js, framework/elsa/fit-elsa-react/src/components/manualCheck/ManualCheckForm.jsx, framework/elsa/fit-elsa-react/src/components/parallelNode/ParallelPluginItem.jsx, framework/elsa/fit-elsa-react/src/components/parallelNode/ParallelTopBar.jsx, framework/elsa/fit-elsa-react/src/components/parallelNode/ParallelWrapper.jsx, framework/elsa/fit-elsa-react/src/components/parallelNode/consts.js, framework/elsa/fit-elsa-react/src/components/parallelNode/parallelComponent.jsx, framework/elsa/fit-elsa-react/src/components/parallelNode/parallelNodeDrawer.jsx, framework/elsa/fit-elsa-react/src/components/parallelNode/parallelNodeState.jsx, framework/elsa/fit-elsa-react/src/components/parallelNode/reducers/reducers.js, framework/elsa/fit-elsa-react/src/components/util/ReferenceUtil.js, framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js, framework/elsa/fit-elsa-react/src/flow/jadeFlowEntry.jsx, framework/elsa/fit-elsa-react/src/flow/jadeFlowGraph.js, framework/elsa/fit-elsa-react/src/i18n/en_US.json, framework/elsa/fit-elsa-react/src/i18n/zh_CN.json
=> [elsa] 并行节点特性添加

framework/elsa/fit-elsa-react/src/components/fileExtraction/FileExtractionWrapper.jsx
[elsa] 由于未接入多模态模型，隐藏文件提取节点中的提取说明配置，避免引起歧义
=> [elsa] 隐藏文件提取节点中的提取说明配置，避免引起歧义

.github/workflows/elsa-compile.yml
Fix the GitHub Actions branch pattern to strictly match `elsa-X.Y.x` version format:
- Escaped dots in regex (`\.` instead of `.`) to avoid ambiguous matches
- Example: Now correctly matches `elsa-0.1.x` but rejects invalid patterns like `elsa-0a1.x`
=> [elsa] ci: fix version branch regex matching

framework/elsa/fit-elsa-react/src/data/GraphOperator.js
- Add special case handling for keys.length === 1 scenarios
- Skip parent config lookup when updating root-level configurations
- Prevent unnecessary null checks for single-key updates
- Maintain existing multi-key update logic unchanged
Key improvements:
1. Behavior change:
- Before: Would throw when parentConfig is null for single-key paths
- Now: Directly updates config without parent lookup for single-key
2. Performance benefit:
- Eliminates redundant slice(0,-1) operation for single-key cases
- Avoids unnecessary parent config existence check
3. Safety:
- Still validates empty keys array (unchanged)
- Preserves all existing error handling for multi-key paths
=> [elsa] fix(GraphOperator): optimize single-key update handling

docs/framework/fit/java/articles/FIT框架：重新定义模块隔离与部署自由，让Swagger从生产环境“优雅消失”.md, docs/framework/fit/java/quick-start-guide/03. 使用插件的热插拔能力.md, docs/framework/fit/java/user-guide-book/03. Conf 配置.md, docs/framework/fit/java/user-guide-book/06. 插件化开发.md, docs/framework/fit/java/user-guide-book/08. 日志.md
1.修正了文档中关于编译输出目录的描述不准确问题，使其与实际编译输出目录一致
=> [fit]修正文档中编译输出目录描述不一致的问题

framework/fel/java/plugins/pom.xml, framework/fel/java/plugins/tool-mcp-server/pom.xml, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/McpController.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/McpServer.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/MessageHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/MessageRequest.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/MessageResponse.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/entity/JsonRpcEntity.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/entity/ToolEntity.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/handler/AbstractMessageHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/handler/InitializeHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/handler/ToolCallHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/handler/ToolListHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/handler/UnsupportedMethodHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/support/DefaultMcpServer.java, framework/fel/java/plugins/tool-mcp-server/src/main/resources/application.yml, framework/fel/java/plugins/tool-repository-simple/src/main/java/modelengine/fel/tool/support/SimpleToolRepository.java, framework/fel/java/services/tool-service/src/main/java/modelengine/fel/tool/service/ToolChangedObserver.java, framework/fit/java/fit-builtin/plugins/fit-http-server-netty/src/main/java/modelengine/fit/http/server/netty/NettyHttpServerRequest.java, framework/fit/java/fit-builtin/plugins/fit-http-server-netty/src/main/java/modelengine/fit/http/server/netty/NettyHttpServerResponse.java, framework/fit/java/fit-builtin/plugins/fit-message-serializer-json-jackson/src/main/java/modelengine/fit/serialization/json/jackson/JacksonObjectSerializer.java, framework/fit/java/fit-builtin/plugins/fit-message-serializer-json-jackson/src/test/java/modelengine/fit/serialization/json/jackson/JacksonObjectSerializerTest.java, framework/fit/java/fit-builtin/services/fit-http-classic/definition/src/main/java/modelengine/fit/http/server/HttpClassicServerRequest.java, framework/fit/java/fit-builtin/services/fit-http-classic/definition/src/main/java/modelengine/fit/http/server/HttpClassicServerResponse.java, framework/fit/java/fit-builtin/services/fit-http-classic/definition/src/main/java/modelengine/fit/http/server/support/DefaultHttpClassicServerRequest.java, framework/fit/java/fit-builtin/services/fit-http-classic/definition/src/main/java/modelengine/fit/http/server/support/DefaultHttpClassicServerResponse.java, framework/fit/java/fit-builtin/services/fit-http-protocol/definition/src/main/java/modelengine/fit/http/protocol/ServerRequest.java, framework/fit/java/fit-builtin/services/fit-http-protocol/definition/src/main/java/modelengine/fit/http/protocol/ServerResponse.java
Add FIT MCP Server, which only support initialize, tools/list, tools/call and close method.
=> [fel] add FIT MCP server

framework/fit/python/requirements.txt
Upgrade tornado (FIT for Python) from 6.4.2 to 6.5.0
=> [fit] upgrade tornado from 6.4.2 to 6.5.0

framework/elsa/fit-elsa-react/src/components/common/JadeObservableOutput.jsx, framework/elsa/fit-elsa-react/src/components/common/JadeObservableTree.jsx, framework/elsa/fit-elsa-react/src/components/common/OutputForm.jsx, framework/elsa/fit-elsa-react/src/components/condition/conditionNodeCondition.jsx, framework/elsa/fit-elsa-react/src/components/llm/LlmOutput.jsx, framework/elsa/fit-elsa-react/src/components/util/BranchUtil.js, framework/elsa/fit-elsa-react/src/flow/jadeFlowEntry.jsx, framework/elsa/fit-elsa-react/src/flow/jadeFlowPage.js, framework/elsa/fit-elsa-react/src/flow/runners.js
This PR introduces a readOnly mode in JadeFlowEntry to support historical version browsing:
Adds readOnly method to disable editing in history view.
Enhances condition node handling to ensure branches remain read-only.
Fixes serialization to preserve disabled state.
Testing:
Verify nodes & condition branches are uneditable in history mode.
Ensure disabled state persists after serialization.
=> feat: Add readOnly mode to JadeFlowEntry for history view

framework/elsa/fit-elsa-react/src/components/common/ConnectorProvider.jsx
Fixes an issue where renaming a ConnectorProvider would break connected lines:
- Added prevNameRef to detect name changes
- Auto-updates direction.key and line references
- Preserves existing connections
Test:
1. Change a connector's name
2. Verify lines remain connected and references update
=> fix(ConnectorProvider): Sync connector name changes with connected lines (fixes #41)

framework/elsa/fit-elsa-react/src/components/common/JadeReferenceTreeSelect.jsx
This PR fixes an issue in JadeReferenceTreeSelect where reference updates were being skipped when selecting the same value, particularly affecting cross-application node copying scenarios.
Problem
Previously, when:
1. Copying nodes between applications
2. Selecting the same reference value again
The component would skip updates if selected === reference.referenceId, leading to:
- Stale referenceKey and value values
- Broken references in cross-application copies
Solution
Key changes:
1. Removed duplicate selection check that prevented updates
2. Now always triggers onReferencedKeyChange on selection
3. Ensures referenceKey and value stay synchronized
=> [elsa] fix(JadeReferenceTreeSelect): Force reference updates on same selection

framework/fel/java/plugins/tool-mcp-server/pom.xml, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/McpController.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/McpServer.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/handler/InitializeHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/handler/ToolCallHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/handler/ToolListHandler.java, framework/fel/java/plugins/tool-mcp-server/src/main/java/modelengine/fel/tool/mcp/server/support/DefaultMcpServer.java, framework/fel/java/plugins/tool-mcp-server/src/test/java/modelengine/fel/tool/mcp/server/McpControllerTest.java, framework/fel/java/plugins/tool-mcp-server/src/test/java/modelengine/fel/tool/mcp/server/support/DefaultMcpServerTest.java
This PR introduces a notification mechanism to the MCP Server that actively sends real-time updates to connected clients whenever tool configurations are modified.
=> [fel] add notification/tools/list_changed method in MCP server

framework/elsa/fit-elsa-react/src/components/common/JadeObservableOutput.jsx
- Wrap description column in conditional render based on showDescription
- Fix UI issue where empty space remained when description was hidden
- Improve layout efficiency by only rendering when needed
- Maintain all existing functionality when description is shown
=> [elsa] fix(JadeObservableOutput): conditionally render description column to avoid empty space

framework/fel/java/plugins/tool-mcp-client/src/main/java/modelengine/fel/tool/mcp/client/support/DefaultMcpClient.java
- Added a closed flag to DefaultMcpClient to track client lifecycle state.
- Prevent method invocations after closure by adding checks in initialize(), getTools(), and callTool().
- Safely handle potential nulls in close() to avoid exceptions during partial initialization.
- Ensures consistent behavior and prevents resource leaks or usage after the client has been closed.
This change improves reliability and correctness by enforcing proper usage of the MCP client throughout its lifecycle.
=> [fel] Improve McpClient lifecycle management with closed state tracking

framework/fel/java/plugins/tool-mcp-client/src/main/java/modelengine/fel/tool/mcp/client/support/DefaultMcpClient.java, framework/fel/java/plugins/tool-mcp-client/src/main/java/modelengine/fel/tool/mcp/client/support/DefaultMcpClientFactory.java, framework/fel/java/plugins/tool-mcp-client/src/main/resources/application.yml
- Introduced configurable ping interval via constructor and configuration (application.yml) with a fallback default value (15,000 ms).
- Moved ping scheduler creation to after initialization to ensure valid session state before sending pings.
- Added parameter validation in DefaultMcpClient constructor using notNull and notBlank checks for better failure visibility.
- Propagated ping interval configuration through DefaultMcpClientFactory using @Value injection.
- Improved testability and lifecycle management by decoupling scheduler setup from constructor logic.
This change increases flexibility and robustness of the MCP client, especially in different deployment and test environments.
=> [fel] Add configurable ping interval

framework/fit/python/plugin/fit_py_heart_beat_agent/heart_beat_agent.py
The current logic is that after the heartbeat goes offline, the information is not successfully re-registered to the registration center, resulting in a no fitables exception error in the request.
=> [fit] Re-register all information to the registry after successful reconnection

framework/elsa/fit-elsa-react/src/components/llm/LlmOutput.jsx, framework/elsa/fit-elsa-react/src/flow/compatibility/compatibilityProcessors.js
**Issue 链接 / Issue Link:** [#237](https://github.com/ModelEngine-Group/app-platform/issues/237)
升级到社区版本后，老应用升级后无法打开编排页面，同时问题回答会回答两遍。该变更修复上述问题，增强了对enableLog的校验，大模型节点也默认增加了enableLog这个结构体。
After upgrading to the Community Edition, legacy applications fail to load the orchestration page post-upgrade while experiencing duplicate responses in Q&A outputs. This change fixes the aforementioned issues by:
1. Enhancing validation for enableLog
2. Adding the enableLog struct to LLM nodes by default
1. Conditional UI Rendering
Checkbox for enableLog now only renders when enableLogData exists
Prevents UI errors when logging functionality is unavailable
3. Core Initialization
New addEnableLog() method ensures enableLog parameter exists
Defaults to true for new configurations
Seamlessly integrates with …
=> [elsa] fix(LlmNodeState): add conditional enableLog control and initialization

framework/fel/java/fel-flow/src/main/java/modelengine/fel/engine/activities/AiConditions.java, framework/fel/java/fel-flow/src/main/java/modelengine/fel/engine/activities/AiState.java, framework/fel/java/fel-flow/src/main/java/modelengine/fel/engine/activities/AiWhenHappen.java, framework/fel/java/fel-flow/src/main/java/modelengine/fel/engine/flows/Conversation.java, framework/fel/java/fel-flow/src/main/java/modelengine/fel/engine/operators/patterns/AbstractFlowPattern.java, framework/fel/java/fel-flow/src/test/java/modelengine/fel/engine/AiFlowCaseTest.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/context/repo/flowcontext/FlowContextMessenger.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/states/Conditions.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/states/State.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/states/WhenHappen.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/stream/nodes/ConditionsNode.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/stream/nodes/To.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/stream/operators/Operators.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/stream/reactive/Subscriber.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/stream/reactive/Subscription.java, framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/stream/reactive/When.java, framework/waterflow/java/waterflow-core/src/test/java/modelengine/fit/waterflow/domain/WaterFlowsTest.java
**Issue 链接 / Issue Link:** #167 
增加关键示例用于突出核心特性
- 增加when then的条件分支用法。
- 增加三个示例突出在流式处理、背压和并发的特性。
1. 运行示例
2. 示例运行全部通过
---
=> [fel] add key scenario cases

examples/fel-example/04-output-parser/src/main/java/modelengine/example/ai/chat/parser/OutputParserExampleController.java, examples/fel-example/05-retrieval/src/main/java/modelengine/example/ai/chat/retrieval/RetrievalExampleController.java, framework/fel/java/plugins/tool-discoverer/src/main/java/modelengine/fel/tool/support/DefaultToolDiscoverer.java
**Issue 链接 / Issue Link:**
When parsing tool files (JSON) in the plugin, the system unexpectedly used the CBOR serializer instead of the JSON serializer, causing a bug.
To fix this issue, we identified the relevant serializer usage points and found that the JSON serializer was not explicitly specified.
This change enforces the use of the JSON serializer by adding the required annotations.
1. Added the @Fit(alias = "json") annotation to explicitly enforce the JSON serializer where needed.
1. Started the plugin with dynamic loading of tool files, verified normal startup, and confirmed that the previous parsing errors were resolved.
**测试要求 / …
=> fix: missing serializer specification

framework/fel/python/plugins/fel_langchain_tools/langchain_tools.py, framework/fel/python/plugins/fel_llama_index_tools/llama_rag_basic_toolkit.py, framework/fel/python/plugins/fel_llama_index_tools/node_utils.py, framework/fel/python/plugins/fel_llamaindex_network_tools/llamaindex_network_tool.py, framework/fel/python/requirements.txt
**Issue 链接 / Issue Link:** https://github.com/ModelEngine-Group/fit-framework/issues/163
添加三方依赖以及升级三方依赖的代码结构，为提供生态插件提供依赖基础 / Add third-party dependencies and upgrade the code structure of third-party dependencies to provide a dependency basis for providing ecological plug-ins
- 添加三方依赖以及升级三方依赖的代码结构 / Add third-party dependencies and upgrade the code structure of third-party dependencies
1. 添加代码到 fit-python 框架，插件可以注册至注册中心 / Add code to the fit-python framework so that plugins can be registered to the registry
---
=> [fel] Improve the code of ecological plug-ins and introduce third-party packages

framework/fel/java/fel-core/src/main/java/modelengine/fel/core/memory/support/RecentMemory.java, framework/fel/java/fel-core/src/test/java/modelengine/fel/core/memory/support/RecentMemoryTest.java, framework/fel/java/fel-flow/pom.xml, framework/fel/java/fel-flow/src/main/java/modelengine/fel/engine/flows/Conversation.java, framework/fel/java/fel-flow/src/main/java/modelengine/fel/engine/operators/models/LlmEmitter.java, framework/fel/java/fel-flow/src/test/java/modelengine/fel/engine/operators/models/LlmEmitterTest.java
**Issue 链接 / Issue Link:** #168 
Add default Memory for conversations.
- Add RecentMemory.
- Use RecentMemory by default when the user does not specify a Memory.
Use FEL to write a streaming conversation where RecentMemory is used when no Memory is specified.
1. Use FEL to write a streaming conversation.
2. The conversation does not specify a Memory.
3. Offer data multiple times in the same conversation.
---
=> [fel] add default memory

framework/fel/java/maven-plugins/tool-maven-plugin/src/main/java/modelengine/fel/maven/complie/parser/ByteBuddySchemaParser.java, framework/fel/java/maven-plugins/tool-maven-plugin/src/test/resources/weather-tools.json, framework/fel/java/services/tool-info/src/main/java/modelengine/fel/tool/info/entity/PropertyEntity.java
工具的schema不符合规范：/  The schema of the tool does not conform to the specification:
- examples应该是个数组 / examples should be an array
- object中的required应该是个数组 / required in object should be an array
**Issue 链接 / Issue Link:** https://github.com/ModelEngine-Group/fit-framework/issues/200
规范工具生成的 json schema 逻辑，适配 mcp 协议  / Standardize the json schema logic generated by the tool to adapt to the mcp protocol
- examples 字段更改为 example / Changed the examples field to example 
- object 类型下的新增 required 数组 / Added required array under object type
- 去掉 required 字段类型为 bool 的数据 /  Removed data with bool type in required field
1. 基本单测通过 / Basic unit test passed
2. schema 数据接入 mcp 服务可以注册调用 / Schema data access mcp service can be registered and called
请确保你的 Pull Request 符合以下要求 / Please ensure your Pull Request …
=> [tool] Upgrade tool compilation tool to adapt to mcp tool mode

framework/fit/java/fit-test/fit-test-framework/src/main/java/modelengine/fitframework/test/annotation/Sql.java, framework/fit/java/fit-test/fit-test-framework/src/main/java/modelengine/fitframework/test/domain/TestPlugin.java, framework/fit/java/fit-test/fit-test-framework/src/main/java/modelengine/fitframework/test/domain/listener/DataSourceListener.java, framework/fit/java/fit-test/fit-test-framework/src/main/java/modelengine/fitframework/test/domain/listener/MockMvcListener.java, framework/fit/java/fit-test/fit-test-framework/src/main/java/modelengine/fitframework/test/domain/listener/SqlExecuteListener.java, framework/fit/java/fit-test/fit-test-framework/src/main/java/modelengine/fitframework/test/domain/resolver/DefaultTestClassResolver.java, framework/fit/java/fit-test/fit-test-framework/src/main/java/modelengine/fitframework/test/domain/resolver/DefaultTestContextConfiguration.java, framework/fit/java/fit-test/fit-test-framework/src/main/java/modelengine/fitframework/test/domain/resolver/TestContextConfiguration.java, framework/fit/java/integration/fit-mybatis/src/test/java/modelengine/fit/integration/mybatis/WordMapperTest.java
**Issue 链接 / Issue Link:** Closes #204 
This change optimizes the test framework to support database access operations within Bean constructors. Previously, the framework couldn't properly handle scenarios where business logic Beans perform database operations during initialization, leading to test failures or inconsistent behavior. This enhancement adds specific execution phases to ensure proper database connection management and transaction handling during Bean construction in test environments.
- Added new execution phase for Bean constructor database access support
- Implemented database connection initialization before Bean construction phase
- Enhanced transaction management for constructor-level database operations
- Added configuration options for controlling database access …
=> [fit] optimize test framework to support executing specific actions at test startup

framework/fit/python/plugin/fit_py_heart_beat_agent/heart_beat_agent.py
原先逻辑是在心跳重新连接并恢复后注册 fitable 信息到注册中心，但是在验证的过程中，还是会发现因为网络或者注册中心未及时启动导致 python 进程注册失败，导致未成功注册信息到注册中心，因此修改为每次心跳注册 fitable 信息到注册中心。 / The original logic was to register the fitable information to the registration center after the heartbeat was reconnected and restored. However, during the verification process, it was found that the python process registration failed because the network or the registration center was not started in time, resulting in unsuccessful registration of the information to the registration center. Therefore, it was changed to register the fitable information to the registration center for each heartbeat.
**Issue 链接 / Issue Link:** #
避免偶然出现的 fitable 调用失败 / Avoid occasional fitable call failures
- 将心跳连接成功之后重新注册更改为每次心跳都会注册 / Change re-registration after successful heartbeat …
=> [python] Register fitable to the registration center during heartbeat

framework/fel/java/plugins/tool-mcp-client/src/main/java/modelengine/fel/tool/mcp/client/support/DefaultMcpClient.java, framework/fel/java/plugins/tool-mcp-client/src/main/java/modelengine/fel/tool/mcp/client/support/Result.java
**Issue 链接 / Issue Link:**
- 对工具列表和调用进行一场捕获，一旦获取一场，立即抛出，确保上层可以感知到
- 增加调用结束的资源回收
1. 针对异常场景，尝试观察发生的几率，是否明显下降
---
=> [fel] Add MCP error handle

framework/fit/java/fit-builtin/plugins/fit-service-coordination-nacos/README.md
**Issue 链接 / Issue Link:** #
-  增加 nacos 插件的 readme文件
- 
- 
1. 
2. 
3. 
---
=> 增加 nacos 插件的 readme 文件

framework/fit/python/plugin/fit_py_heart_beat_agent/heart_beat_agent.py
**Issue 链接 / Issue Link:** #263 
python fit 启动报错
- 保持心跳在mac的线程机制和windows下一致
1. 启动 fit-framework/examples/fit-example/04-complicated-apps/app-registry-center 的RegistryCenterStarter类
2. 修改 python fit 下的registry_client插件的 application.yml 配置文件
3. 运行python -m fitframework
---
=> [fit] fix python heartbeat thread on mac

framework/waterflow/java/waterflow-core/src/main/java/modelengine/fit/waterflow/domain/utils/UUIDUtil.java, framework/waterflow/java/waterflow-core/src/test/java/modelengine/fit/waterflow/domain/utils/UUIDUtilTest.java
**Issue 链接 / Issue Link:** #295 
Supports configuring UUID generator.
- Supports configuring UUID generator
Takes effect after replacing the UUID generator.
1. Replace the UUID generator
2. Obtain a UUID
---
=> [waterflow] supports configuring uuid generator

framework/fit/python/fit_cli/commands/build_cmd.py, framework/fit/python/fit_cli/commands/init_cmd.py, framework/fit/python/fit_cli/commands/package_cmd.py, framework/fit/python/fit_cli/main.py, framework/fit/python/fit_cli/readme.md, framework/fit/python/fit_cli/utils/build.py
**Issue 链接 / Issue Link:** #260 
为fit for python 插件工具新增build、package 命令
- 增加build命令
- 增加package命令
1. 终端输入python -m fit_cli init demo
2. 修改代码模板中的${genericable_id} / ${fitable_id}为符合要求的格式
3. 终端输入python -m fit_cli build demo
4. 终端输入python -m fit_cli package demo
---
=> [fit] 新增build、package 命令

framework/fit/python/fit_cli/utils/build.py
**Issue 链接 / Issue Link:** <mark>#259</mark> 👈👈
完善build命令
- build命令支持自定义结构体
1. 为插件代码增加结构体参数
2. 执行build命令
---
=> [fit] build命令支持自定义结构体参数
